Dump optimized thresholds for buildings as a yaml file
IGNF/lidar-prod pull request #109
Opened 2024-04-17 12:42 UTC by leavauchier

Solves https://github.com/IGNF/lidar-prod/issues/92.

Use yaml to make it easier to copy-paste to a configuration file

2024-04-17 12:48 UTC, MichelDaab approved these changes

2024-04-17 12:57 UTC, leavauchier commented on tests/lidar_prod/tasks/test_building_validation_optimization.py
> +def setup_module(module):
the reason decided to hardcode this is to be able to have a look at the generated results (mainly in case the test fails)

2024-04-17 13:05 UTC, CharlesGaydon requested changes
The change of file format itself seems ok. However, I think you may be duplicating tests and test data for the optimization of thresholds.
I suggest simplifying the test, perhaps by simply adding more test assertions to the existing ones in `test_optimization`.

Current structure separes end-to-end tests (`test_application`,`tesrt_optimization`) from uni tests (in subfolder).

On a side note, it seems that there are some older test files (shapefiles) that may not be used anymore:
![image](https://github.com/IGNF/lidar-prod/assets/11660435/310f2b3c-f934-4474-b29f-eadab40e8d05)

2024-04-17 13:11 UTC, MichelDaab commented on tests/lidar_prod/tasks/test_building_validation_optimization.py
> +def test_BuildingValidationOptimizer_run(hydra_cfg):
I don't understand the point of merging both tests: if that test fails we know it's the save/load function, if the other fails we know it's something else.  What would be the point of merging?

2024-04-18 07:41 UTC, leavauchier commented on tests/lidar_prod/tasks/test_building_validation_optimization.py
> +def test_BuildingValidationOptimizer_run(hydra_cfg):
The point is just to avoid duplicate code by adding this new assertion on the threshold file to the already existing test

2024-04-18 07:41 UTC, leavauchier commented on tests/lidar_prod/tasks/test_building_validation_optimization.py
> +def test_BuildingValidationOptimizer_run(hydra_cfg):
However, I'd rather move the test on BuildingValidationOptimizer to test_building_validation_optimization.py to ensure consistency between the test files directory and the library files directory

2024-04-18 07:56 UTC, leavauchier commented
> The change of file format itself seems ok. However, I think you may be duplicating tests and test data for the optimization of thresholds. I suggest simplifying the test, perhaps by simply adding more test assertions to the existing ones in `test_optimization`.
> 
> Current structure separes end-to-end tests (`test_application`,`tesrt_optimization`) from uni tests (in subfolder).
> 
> On a side note, it seems that there are some older test files (shapefiles) that may not be used anymore: ![image](https://private-user-images.githubusercontent.com/11660435/323228235-310f2b3c-f934-4474-b29f-eadab40e8d05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjYzODgsIm5iZiI6MTcxMzQyNjA4OCwicGF0aCI6Ii8xMTY2MDQzNS8zMjMyMjgyMzUtMzEwZjJiM2MtZjkzNC00NDc0LWIyOWYtZWFkYWI0MGU4ZDA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA3NDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMzQ4ZGIzYjMzYzU5OWI3NDExOTdiM2I3ODVmNmMzZTY0ZmU4NzM0YjQxM2ZiNGIzOTk1ZTdkNjQ0ZmZiZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nhADX2_tsiFsRSJNaU9v1ZjkWrjTbFLGE1ZzuQiFQCI)

870000_6618000.subset.postIA.las and 
870000_6618000.subset.postIA.shp are used in test_application.py
the other 
870000_6618000.subset.postIA.* are side files for the .shp file

2024-04-18 11:36 UTC, CharlesGaydon commented
It seems that you removed the duplicated test without keeping the last assertions i.e.

```
th_yaml = opt_cfg.paths.building_validation_thresholds
assert os.path.isfile(th_yaml)
assert isinstance(thresholds.load(th_yaml), thresholds)

for filename in os.listdir(opt_cfg.paths.input_las_dir):
    assert (TMP_DIR / "run" / "prepared" / filename).is_file()
    assert (TMP_DIR / "run" / "updated" / filename).is_file()
```
Checking the existence of the threshold file seems useful. Checking the prepared file not so much since the evaluation of metrics ensure that they were properly created. The existence of updated file might be useful.

2024-04-18 11:37 UTC, CharlesGaydon approved these changes

2024-04-18 11:37 UTC, CharlesGaydon commented
LGTM :)

2024-04-18 12:45 UTC, merged